def build_label_flow(label_builder):
    label_builder \
        .start_with("dmorte_one_introducing") \
            .say("DMORTE1.D_s0") \
            .end_with("morgue_dialog_loop") \
        .start_with("dmorte_one_loot_dummies") \
            .say("DMORTE1.D_s24") \
            .end_with("morgue_dialog_loop") \
        .start_with("dmorte_one_talk_dummies") \
            .say("DMORTE1.D_s33") \
            .end_with("morgue_dialog_loop") \
        .start_with("dmorte_one_talk_and_loot_dummies") \
            .say('DMORTE1.D_s34') \
            .end_with('morgue_dialog_loop') \
        .start_with("dmorte_one_join") \
            .say('DMORTE1.D_s26') \
            .end_with('morgue_dialog_loop') \
        .start_with("dmorte_one_talk_morte") \
            .say('DMORTE1.D_s30') \
            .end_with('morgue_dialog_loop') \
        .start_with("dmorte_one_kill_morte") \
            .say('DMORTE1.D_s99999999_34') \
            .end_with('morgue_dialog_loop') \
        .start_with("dmorte_two_talk_morte") \
            .say('DMORTE2.D_s12') \
            .end_with('morgue_dialog_loop') \
        .start_with("dmorte_one_open_morgue_door") \
            .say('DMORTE2.D_s0') \
            .end_with('morgue_dialog_loop') \
        .start_with("dmorte_two_meet_dhall") \
            .say('DDHALL.D_s5') \
            .end_with('morgue_dialog_loop') \
        .start_with("dmorte_two_talk_dhall") \
            .say('DDHALL.D_s40') \
            .end_with('morgue_dialog_loop') \
        .start_with("dmorte_two_kill_dhall") \
            .say('DDHALL.D_s99999999_54') \
            .end_with('morgue_dialog_loop') \
        .start_with("dmorte_one_kill_dzm569") \
            .say('DMORTE1.D_s99999999_569') \
            .end_with('morgue_dialog_loop') \
        .start_with("dmorte_one_kill_dzm825") \
            .say('DMORTE1.D_s99999999_825') \
            .end_with('morgue_dialog_loop') \
        .start_with("dmorte_one_kill_dzm782") \
            .say('DMORTE1.D_s99999999_782') \
            .end_with('morgue_dialog_loop') \
        .start_with("dmorte_one_talk_dzm569") \
            .say('DZM569.D_s0') \
            .end_with('morgue_dialog_loop') \
        .start_with("dmorte_one_talk_dzm825") \
            .say('DZM825.D_s0') \
            .end_with('morgue_dialog_loop') \
        .start_with("dmorte_one_talk_dzm782") \
            .say('DZM782.D_s0') \
            .end_with('morgue_dialog_loop')
