# manually sync with script.rpy 'characters' variable
define the_nameless_one = Character('Безымянный', color='#c8ffc8')

define nr                 = Character('',               color='#c8ffc8')
define morte_unknown      = Character('?',              color='#c8ffc8')
define morte              = Character('Морт',           color='#c8ffc8')
define morte_story_1      = Character('Старуха',        color='#c8ffc8')
define morte_story_2      = Character('Старик',         color='#c8ffc8')
define annah_unknown      = Character('?',              color='#c8ffc8')
define annah              = Character('Анна',           color='#c8ffc8')
define ignus_unknown      = Character('?',              color='#c8ffc8')
define ignus              = Character('Игнус',          color='#c8ffc8')
define grace_unknown      = Character('?',              color='#c8ffc8')
define grace              = Character('Падшая грация',  color='#c8ffc8')
define dakkon_unknown     = Character('?',              color='#c8ffc8')
define dakkon             = Character('Дак’кон',        color='#c8ffc8')
define nordom_unknown     = Character('?',              color='#c8ffc8')
define nordom             = Character('Нордом',         color='#c8ffc8')
define vhail_unknown      = Character('?',              color='#c8ffc8')
define vhail              = Character('Вейлор',         color='#c8ffc8')
define scars              = Character('',               color='#c8ffc8')
define death_names        = Character('Смерть имён',    color='#c8ffc8')
define dhall              = Character('Дхолл',          color='#c8ffc8')
define dhall_unknown      = Character('?',              color='#c8ffc8')
define bei                = Character('Бэй',            color='#c8ffc8')
define asonje             = Character('Асонж',          color='#c8ffc8')
define eivene_unknown     = Character('?',              color='#c8ffc8')
define eivene             = Character('Эи-Вейн',        color='#c8ffc8')
define vaxis_unknown      = Character('?',              color='#c8ffc8')
define vaxis              = Character('Ваксис',         color='#c8ffc8')
define xach_unknown       = Character('?',              color='#c8ffc8')
define xach               = Character('Захария',        color='#c8ffc8')
define deionarra_unknown  = Character('?',              color='#c8ffc8')
define deionarra          = Character('Дейонарра',      color='#c8ffc8')
define soego_unknown      = Character('?',              color='#c8ffc8')
define soego              = Character('Соего',          color='#c8ffc8')
define dust               = Character('Тленный',        color='#c8ffc8')
define dustfem            = Character('Тленная',        color='#c8ffc8')

define s42            = Character('Скелет 42',      color='#c8ffc8')
define s748           = Character('Скелет 748',     color='#c8ffc8')
define s863           = Character('Скелет 863',     color='#c8ffc8')
define s996           = Character('Скелет 996',     color='#c8ffc8')
define s1221          = Character('Скелет 1221',    color='#c8ffc8')

define zm79           = Character('Зомби 79',      color='#c8ffc8')
define zm199          = Character('Зомби 199',     color='#c8ffc8')
define zm257          = Character('Зомби 257',     color='#c8ffc8')
define zm310          = Character('Зомби 310',     color='#c8ffc8')
define zm396          = Character('Зомби 396',     color='#c8ffc8')
define zm463          = Character('Зомби 463',     color='#c8ffc8')
define zm475          = Character('Зомби 475',     color='#c8ffc8')
define zm506          = Character('Зомби 506',     color='#c8ffc8')
define zm569          = Character('Зомби 569',     color='#c8ffc8')
define zm613          = Character('Зомби 613',     color='#c8ffc8')
define zm732          = Character('Зомби 732',     color='#c8ffc8')
define zm782          = Character('Зомби 782',     color='#c8ffc8')
define zm825          = Character('Зомби 825',     color='#c8ffc8')
define zm965          = Character('Зомби 965',     color='#c8ffc8')
define zm985          = Character('Зомби 985',     color='#c8ffc8')
define zm1041         = Character('Зомби 1041',    color='#c8ffc8')
define zm1094         = Character('Зомби 1094',    color='#c8ffc8')
define zm1146         = Character('Зомби 1146',    color='#c8ffc8')
define zm1201         = Character('Зомби 1201',    color='#c8ffc8')
define zm1445         = Character('Зомби 1445',    color='#c8ffc8')
define zm1508         = Character('Зомби 1508',    color='#c8ffc8')
define zm1664         = Character('Зомби 1664',    color='#c8ffc8')

define zf114          = Character('Зомби 114',    color="#c8ffc8")
define zf444          = Character('Зомби 444',    color="#c8ffc8")
define zf594          = Character('Зомби 594',    color="#c8ffc8")
define zf626          = Character('Зомби 626',    color="#c8ffc8")
define zf679          = Character('Зомби 679',    color="#c8ffc8")
define zf832          = Character('Зомби 832',    color="#c8ffc8")
define zf891          = Character('Зомби 891',    color="#c8ffc8")
define zf916          = Character('Зомби 916',    color="#c8ffc8")
define zf1072         = Character('Зомби 1072',   color="#c8ffc8")
define zf1096         = Character('Зомби 1096',   color="#c8ffc8")
define zf1148         = Character('Зомби 1148',   color="#c8ffc8")

define snowinmars     = Character('dev',          color='#c8ffc8')
