def generateSettings(known_settings_name):
    builder = 'def build_autogenerated_settings(manager):\n    manager \\\n'

    for key, value in sorted(known_settings_name.items(), key=lambda x: x[1].name):
        name = value.name
        type_ = value.type

        if type_ == "boolean":
            builder += f"        .register('{name}', False) \\\n"
        elif type_ == "integer":
            builder += f"        .register('{name}', 0) \\\n"
        else:
            raise Error(f"KnownSettingsName type is out of range: {type_}")

    builder = builder[:-3]  # remove last \
    builder += '\n'

    return builder