// creator  : D:\Games\NearInfinity-exp\app\NearInfinity.jar (v2.4-20250611)
// game     : D:\Games\Steam\steamapps\common\Project P
// resource : BDAKKON.DLG
// source   : data\DLGFiles.bif
// dialog   : lang\fr_FR\dialog.tlk
// dialogF  : (none)

BEGIN ~BDAKKON~

IF ~  True()
~ THEN BEGIN 0 // from:
  SAY #31486 /* ~This is a placeholder file for interaction text involving Dak'kon.~ */
  IF ~~ THEN EXIT
END
