// creator  : D:\Games\NearInfinity-exp\app\NearInfinity.jar (v2.4-20250611)
// game     : D:\Games\Steam\steamapps\common\Project P
// resource : DDUP.DLG
// source   : data\DLGFiles.bif
// dialog   : lang\de_DE\dialog.tlk
// dialogF  : (none)

BEGIN ~DDUP~

IF ~~ THEN BEGIN 0 // from:
  SAY #21865 /* ~Die von Panik erfaßte junge Frau rennt auf dich zu. Sie ist völlig außer Atem und Tränen strömen über ihr Gesicht. "Bitte! Du mußt mir helfen! Bring sie auseinander! Die *bringen sich noch um*!"~ */
  IF ~~ THEN EXIT
END
