label never_inventory:
    $ never = _('inventory_item_keypr_general_name')
    $ never = _('inventory_item_keypr_identified_name')
    $ never = _('inventory_item_keypr_general_description')
    $ never = _('inventory_item_keypr_identified_description')
    $ never = _('inventory_item_keypr_fake_properties')

    $ never = _('inventory_item_prybar_general_name')
    $ never = _('inventory_item_prybar_identified_name')
    $ never = _('inventory_item_prybar_general_description')
    $ never = _('inventory_item_prybar_identified_description')
    $ never = _('inventory_item_prybar_fake_properties')

    $ never = _('inventory_item_tomeba_general_name')
    $ never = _('inventory_item_tomeba_identified_name')
    $ never = _('inventory_item_tomeba_general_description')
    $ never = _('inventory_item_tomeba_identified_description')
    $ never = _('inventory_item_tomeba_fake_properties')

    $ never = _('inventory_item_copearc_general_name')
    $ never = _('inventory_item_copearc_identified_name')
    $ never = _('inventory_item_copearc_general_description')
    $ never = _('inventory_item_copearc_identified_description')
    $ never = _('inventory_item_copearc_fake_properties')

    $ never = _('inventory_item_copearo_general_name')
    $ never = _('inventory_item_copearo_identified_name')
    $ never = _('inventory_item_copearo_general_description')
    $ never = _('inventory_item_copearo_identified_description')
    $ never = _('inventory_item_copearo_fake_properties')

    $ never = _('inventory_item_scalpel_general_name')
    $ never = _('inventory_item_scalpel_identified_name')
    $ never = _('inventory_item_scalpel_general_description')
    $ never = _('inventory_item_scalpel_identified_description')
    $ never = _('inventory_item_scalpel_fake_properties')

    $ never = _('inventory_item_needle_general_name')
    $ never = _('inventory_item_needle_identified_name')
    $ never = _('inventory_item_needle_general_description')
    $ never = _('inventory_item_needle_identified_description')
    $ never = _('inventory_item_needle_fake_properties')

    $ never = _('inventory_item_n1201_general_name')
    $ never = _('inventory_item_n1201_identified_name')
    $ never = _('inventory_item_n1201_general_description')
    $ never = _('inventory_item_n1201_identified_description')
    $ never = _('inventory_item_n1201_fake_properties')

    $ never = _('inventory_item_logpage_general_name')
    $ never = _('inventory_item_logpage_identified_name')
    $ never = _('inventory_item_logpage_general_description')
    $ never = _('inventory_item_logpage_identified_description')
    $ never = _('inventory_item_logpage_fake_properties')

    $ never = _('inventory_item_bandage_general_name')
    $ never = _('inventory_item_bandage_identified_name')
    $ never = _('inventory_item_bandage_general_description')
    $ never = _('inventory_item_bandage_identified_description')
    $ never = _('inventory_item_bandage_fake_properties')

    $ never = _('inventory_item_embalm_general_name')
    $ never = _('inventory_item_embalm_identified_name')
    $ never = _('inventory_item_embalm_general_description')
    $ never = _('inventory_item_embalm_identified_description')
    $ never = _('inventory_item_embalm_fake_properties')

    $ never = _('inventory_item_keyem_general_name')
    $ never = _('inventory_item_keyem_identified_name')
    $ never = _('inventory_item_keyem_general_description')
    $ never = _('inventory_item_keyem_identified_description')
    $ never = _('inventory_item_keyem_fake_properties')

    $ never = _('inventory_item_tearring_general_name')
    $ never = _('inventory_item_tearring_identified_name')
    $ never = _('inventory_item_tearring_general_description')
    $ never = _('inventory_item_tearring_identified_description')
    $ never = _('inventory_item_tearring_fake_properties')

    $ never = _('inventory_item_keymo_general_name')
    $ never = _('inventory_item_keymo_identified_name')
    $ never = _('inventory_item_keymo_general_description')
    $ never = _('inventory_item_keymo_identified_description')
    $ never = _('inventory_item_keymo_fake_properties')

    $ never = _('inventory_item_keymo2_general_name')
    $ never = _('inventory_item_keymo2_identified_name')
    $ never = _('inventory_item_keymo2_general_description')
    $ never = _('inventory_item_keymo2_identified_description')
    $ never = _('inventory_item_keymo2_fake_properties')

    $ never = _('inventory_item_quill_general_name')
    $ never = _('inventory_item_quill_identified_name')
    $ never = _('inventory_item_quill_general_description')
    $ never = _('inventory_item_quill_identified_description')
    $ never = _('inventory_item_quill_fake_properties')

    $ never = _('inventory_item_fingbone_general_name')
    $ never = _('inventory_item_fingbone_identified_name')
    $ never = _('inventory_item_fingbone_general_description')
    $ never = _('inventory_item_fingbone_identified_description')
    $ never = _('inventory_item_fingbone_fake_properties')

    $ never = _('inventory_item_dustrobe_general_name')
    $ never = _('inventory_item_dustrobe_identified_name')
    $ never = _('inventory_item_dustrobe_general_description')
    $ never = _('inventory_item_dustrobe_identified_description')
    $ never = _('inventory_item_dustrobe_fake_properties')

    $ never = _('inventory_item_dremind_general_name')
    $ never = _('inventory_item_dremind_identified_name')
    $ never = _('inventory_item_dremind_general_description')
    $ never = _('inventory_item_dremind_identified_description')
    $ never = _('inventory_item_dremind_fake_properties')

    $ never = _('inventory_item_doornote_general_name')
    $ never = _('inventory_item_doornote_identified_name')
    $ never = _('inventory_item_doornote_general_description')
    $ never = _('inventory_item_doornote_identified_description')
    $ never = _('inventory_item_doornote_fake_properties')

    $ never = _('inventory_item_drequest_general_name')
    $ never = _('inventory_item_drequest_identified_name')
    $ never = _('inventory_item_drequest_general_description')
    $ never = _('inventory_item_drequest_identified_description')
    $ never = _('inventory_item_drequest_fake_properties')

    $ never = _('inventory_item_tasklist_general_name')
    $ never = _('inventory_item_tasklist_identified_name')
    $ never = _('inventory_item_tasklist_general_description')
    $ never = _('inventory_item_tasklist_identified_description')
    $ never = _('inventory_item_tasklist_fake_properties')

    $ never = _('inventory_item_bonechrm_general_name')
    $ never = _('inventory_item_bonechrm_identified_name')
    $ never = _('inventory_item_bonechrm_general_description')
    $ never = _('inventory_item_bonechrm_identified_description')
    $ never = _('inventory_item_bonechrm_fake_properties')

    $ never = _('inventory_item_breast1_general_name')
    $ never = _('inventory_item_breast1_identified_name')
    $ never = _('inventory_item_breast1_general_description')
    $ never = _('inventory_item_breast1_identified_description')
    $ never = _('inventory_item_breast1_fake_properties')

    $ never = _('inventory_item_breast2_general_name')
    $ never = _('inventory_item_breast2_identified_name')
    $ never = _('inventory_item_breast2_general_description')
    $ never = _('inventory_item_breast2_identified_description')
    $ never = _('inventory_item_breast2_fake_properties')

    $ never = _('inventory_item_breast3_general_name')
    $ never = _('inventory_item_breast3_identified_name')
    $ never = _('inventory_item_breast3_general_description')
    $ never = _('inventory_item_breast3_identified_description')
    $ never = _('inventory_item_breast3_fake_properties')

    $ never = _('inventory_item_breast4_general_name')
    $ never = _('inventory_item_breast4_identified_name')
    $ never = _('inventory_item_breast4_general_description')
    $ never = _('inventory_item_breast4_identified_description')
    $ never = _('inventory_item_breast4_fake_properties')

    $ never = _('inventory_item_clotchrm_general_name')
    $ never = _('inventory_item_clotchrm_identified_name')
    $ never = _('inventory_item_clotchrm_general_description')
    $ never = _('inventory_item_clotchrm_identified_description')
    $ never = _('inventory_item_clotchrm_fake_properties')

    $ never = _('inventory_item_cube_general_name')
    $ never = _('inventory_item_cube_identified_name')
    $ never = _('inventory_item_cube_general_description')
    $ never = _('inventory_item_cube_identified_description')
    $ never = _('inventory_item_cube_fake_properties')

    $ never = _('inventory_item_decant_general_name')
    $ never = _('inventory_item_decant_identified_name')
    $ never = _('inventory_item_decant_general_description')
    $ never = _('inventory_item_decant_identified_description')
    $ never = _('inventory_item_decant_fake_properties')

    $ never = _('inventory_item_junk_general_name')
    $ never = _('inventory_item_junk_identified_name')
    $ never = _('inventory_item_junk_general_description')
    $ never = _('inventory_item_junk_identified_description')
    $ never = _('inventory_item_junk_fake_properties')

    $ never = _('inventory_item_gsknife_general_name')
    $ never = _('inventory_item_gsknife_identified_name')
    $ never = _('inventory_item_gsknife_general_description')
    $ never = _('inventory_item_gsknife_identified_description')
    $ never = _('inventory_item_gsknife_fake_properties')

    $ never = _('inventory_item_rags_general_name')
    $ never = _('inventory_item_rags_identified_name')
    $ never = _('inventory_item_rags_general_description')
    $ never = _('inventory_item_rags_identified_description')
    $ never = _('inventory_item_rags_fake_properties')

    $ never = _('inventory_item_spike_general_name')
    $ never = _('inventory_item_spike_identified_name')
    $ never = _('inventory_item_spike_general_description')
    $ never = _('inventory_item_spike_identified_description')
    $ never = _('inventory_item_spike_fake_properties')

    $ never = _('inventory_item_strap_general_name')
    $ never = _('inventory_item_strap_identified_name')
    $ never = _('inventory_item_strap_general_description')
    $ never = _('inventory_item_strap_identified_description')
    $ never = _('inventory_item_strap_fake_properties')

    $ never = _('inventory_item_dsupring_general_name')
    $ never = _('inventory_item_dsupring_identified_name')
    $ never = _('inventory_item_dsupring_general_description')
    $ never = _('inventory_item_dsupring_identified_description')
    $ never = _('inventory_item_dsupring_fake_properties')

    $ never = _('inventory_item_dwedring_general_name')
    $ never = _('inventory_item_dwedring_identified_name')
    $ never = _('inventory_item_dwedring_general_description')
    $ never = _('inventory_item_dwedring_identified_description')
    $ never = _('inventory_item_dwedring_fake_properties')

    $ never = _('inventory_item_xacheart_general_name')
    $ never = _('inventory_item_xacheart_identified_name')
    $ never = _('inventory_item_xacheart_general_description')
    $ never = _('inventory_item_xacheart_identified_description')
    $ never = _('inventory_item_xacheart_fake_properties')

    $ never = _('inventory_item_xacliver_general_name')
    $ never = _('inventory_item_xacliver_identified_name')
    $ never = _('inventory_item_xacliver_general_description')
    $ never = _('inventory_item_xacliver_identified_description')
    $ never = _('inventory_item_xacliver_fake_properties')
