# Each settings_id will be transformed to a bunch of functions into the state_manager
#   see the builder flow for more
from game.engine_data.settings.generated import (build_autogenerated_settings)


def build_all_settings(manager):
    build_autogenerated_settings(manager)
    manager \
        .register('know_soego_name', False) \
        .register('know_vaxis_name', False) \
        .register('know_annah_name', False) \
        .register('know_dakkon_name', False) \
        .register('know_deionarra_name', False) \
        .register('know_eivene_name', False) \
        .register('know_grace_name', False) \
        .register('know_ignus_name', False) \
        .register('know_morte_name', False) \
        .register('know_nordom_name', False) \
        .register('know_vhail_name', False) \
        .register('gold', 0) \
        .register('talked_to_dustfem_times', 0) \
        .register('talked_to_dust_times', 0) \
        .register('talked_to_zm257_spirit_times', 0) \
        .register('talked_to_zm331_times', 0) \
        .register('appearance', False)
        # .register('good', 0)
        # .register('law', 0)
        # .register('lore', 0)
        # .register('exp', 0)
