# Each settings_id will be transformed to a bunch of functions into the state_manager
#   see the builder flow for more
from game.engine_data.settings.generated import (build_autogenerated_settings)


def build_all_settings(manager):
    build_autogenerated_settings(manager)
    build_quests_settings(manager)
    manager \
        .register('know_soego_name', False) \
        .register('know_vaxis_name', False) \
        .register('know_annah_name', False) \
        .register('know_dakkon_name', False) \
        .register('know_deionarra_name', False) \
        .register('know_grace_name', False) \
        .register('know_ignus_name', False) \
        .register('know_nordom_name', False) \
        .register('know_vhail_name', False) \
        .register('heard_about_rule_of_threes', False) \
        .register('gold', 0) \
        .register('talked_to_dustfem_times', 0) \
        .register('talked_to_dust_times', 0) \
        .register('talked_to_zm257_spirit_times', 0) \
        .register('talked_to_zm331_times', 0) \
        .register('appearance', False)
        # .register('good', 0)
        # .register('law', 0)
        # .register('lore', 0)
        # .register('exp', 0)


# this method is a container for variables i do not know where comes from
# TODO [snow]: make it a meaningfull list
# TODO [snow]: aelwynn vs aelwyn is a bug?
def build_quests_settings(manager):
    manager \
        .register('agril_dead_kaputz', False) \
        .register('blackr_dead_kaputz', False) \
        .register('ghrist_dead_kaputz', False) \
        .register('krystall_dead_kaputz', False) \
        .register('mar_dead_kaputz', False) \
        .register('mebbeth_dead_kaputz', False) \
        .register('mftree_dead_kaputz', False) \
        .register('nestor_dead_kaputz', False) \
        .register('rwill_dead_kaputz', False) \
        .register('thesik_dead_kaputz', False) \
        .register('aelwynn', 0) \
        .register('alpha', 0) \
        .register('beta', 0) \
        .register('delta', 0) \
        .register('epsilon', 0) \
        .register('gamma', 0) \
        .register('angyar_quest', 0) \
        .register('arlo_quest', 0) \
        .register('baen_quest', 0) \
        .register('boxleft', 0) \
        .register('br_krys', 0) \
        .register('br_rw', 0) \
        .register('c_off', 0) \
        .register('caretaker', 0) \
        .register('carl_snuffed', 0) \
        .register('chaotic_craddock_1', 0) \
        .register('chaotic_emoric_1', 0) \
        .register('chaotic_emoric_2', 0) \
        .register('chaotic_sevtai_1', 0) \
        .register('cr_vic', 0) \
        .register('craddock_quest', 0) \
        .register('crier', 0) \
        .register('crier_quest', 0) \
        .register('curst_key', 0) \
        .register('cw_qui_question', 0) \
        .register('demonbox', 0) \
        .register('dolora', 0) \
        .register('dream', 0) \
        .register('dustman_initiation', 0) \
        .register('dustman_pickpocket', 0) \
        .register('e_book', 0) \
        .register('ecco_speak', 0) \
        .register('emoric_pharod', 0) \
        .register('evidence_papers', 0) \
        .register('f_ass', 0) \
        .register('fedex', 0) \
        .register('finam', 0) \
        .register('free_fiend', 0) \
        .register('g_test1', 0) \
        .register('g_test2', 0) \
        .register('g_test3', 0) \
        .register('gemquest', 0) \
        .register('gilt_miss', 0) \
        .register('grace_quest', 0) \
        .register('iannis_sensory_quest', 0) \
        .register('ingress', 0) \
        .register('join_anarchists', 0) \
        .register('join_dustmen', 0) \
        .register('join_godsmen', 0) \
        .register('journal', 0) \
        .register('jul_mission_1', 0) \
        .register('jul_mission_2', 0) \
        .register('karina_friend', 0) \
        .register('kesai_quest', 0) \
        .register('kill_vorten', 0) \
        .register('know_ravel', 0) \
        .register('know_ravel_key', 0) \
        .register('krystall', 0) \
        .register('kyname', 0) \
        .register('lawful_emoric_1', 0) \
        .register('lo_quest', 0) \
        .register('malmaner', 0) \
        .register('mausoleum_quest', 0) \
        .register('mebbeth_fail', 0) \
        .register('mebbeth_quest', 0) \
        .register('mediate', 0) \
        .register('merriman', 0) \
        .register('mertwyn', 0) \
        .register('mertwyn_head', 0) \
        .register('mochai', 0) \
        .register('nemelle', 0) \
        .register('nestor_quest', 0) \
        .register('nodd_quest', 0) \
        .register('noname', 0) \
        .register('outland_portal', 0) \
        .register('p_journal', 0) \
        .register('pillow_quest', 0) \
        .register('pk_quest', 0) \
        .register('plans_quest', 0) \
        .register('porphiron_quest', 0) \
        .register('pregnant_quest', 0) \
        .register('qui_sai_quest', 0) \
        .register('quint_item', 0) \
        .register('rat_quest', 0) \
        .register('ravel_trias', 0) \
        .register('receipt', 0) \
        .register('reekwind', 0) \
        .register('regret', 0) \
        .register('release_dimtree', 0) \
        .register('releaseb', 0) \
        .register('releaseh', 0) \
        .register('revenge_v', 0) \
        .register('rings3', 0) \
        .register('roberta_betrayed', 0) \
        .register('rw', 0) \
        .register('sabotage', 0) \
        .register('scent_quest_qj', 0) \
        .register('sevtai_quest', 0) \
        .register('sharegrave', 0) \
        .register('shite', 0) \
        .register('slavers', 0) \
        .register('smuggle', 0) \
        .register('snuff_carl', 0) \
        .register('snuff_ghrist', 0) \
        .register('snuff_rat', 0) \
        .register('soego_quest', 0) \
        .register('spirit_quest', 0) \
        .register('story_reekwind_curse', 0) \
        .register('snuff_grosuk', 0) \
        .register('sybil_quest', 0) \
        .register('talk_to_betrayer', 0) \
        .register('trias', 0) \
        .register('trias_sword', 0) \
        .register('trist_quest', 0) \
        .register('uhir', 0) \
        .register('veil_quest_qj', 0) \
        .register('vristigor', 0) \
        .register('waste_quisai', 0) \
        .register('water', 0)
    return manager