// creator  : D:\Games\NearInfinity-exp\app\NearInfinity.jar (v2.4-20250611)
// game     : D:\Games\Steam\steamapps\common\Project P
// resource : DEADGRD.DLG
// source   : data\DLGFiles.bif
// dialog   : lang\pl_PL\dialog.tlk
// dialogF  : (none)

BEGIN ~DEADGRD~

IF ~  True()
~ THEN BEGIN 0 // from:
  SAY #52774 /* ~Widzisz jednego z elity Klątwy leżącego w kałuży własnej krwi. Zbroja jego została kompletnie zmiażdżona. Znajdujące się pod nią ciało wygląda tak, jakby zostało przypieczone ogniem tysiąca słońc. To, co zostało jeszcze z jego twarzy, obrzuca cię spojrzeniem. "Deva... jest silny. Nie wchodź... póki nie będziesz... mógł go pokonać." Kona w milczeniu.~ */
  IF ~~ THEN EXIT
END
