// import {KnownSettings} from "./wellKnownFunctions.ts";

type KnownSettings = Readonly<{
    name: string;
    type: 'boolean' | 'integer';
}>

export const setupSettings = (knownSettingsName: KnownSettings[]): string => {
    let builder = 'def build_autogenerated_settings(manager):\n    manager \\\n'

    for(const {name, type} of knownSettingsName) {
        // .register('dustmen', None)
        switch (type) {
            case "boolean":
                builder += `        .register('${name}', False) \\\n`
                break;
            case "integer":
                builder += `        .register('${name}', 0) \\\n`
                break;
            default:
                throw new Error(`KnownSettingsName type is out of range: ${type}`);
        }
    }

    builder = builder.slice(0, -3); // last \
    builder += '\n'

    return builder;
}
